#!/bin/sh
loguser=$(whoami)
echo "Début de la mise à jour la mise à jour : " > /var/log/$loguser.auto-update.txt
date >> /var/log/$loguser.auto-update.txt
apt-get update
apt list --upgradable >> /var/log/$loguser.auto-update.txt 2>&1
apt-get full-upgrade -y >> /var/log/$loguser.auto-update.txt 2>&1
apt-get autoremove --purge -y >> /var/log/$loguser.auto-update.txt 2>&1
deb-get upgrade >> /var/log/$loguser.auto-update.txt 2>&1
apt-get clean
apt-get autoclean
echo "
Fin de la mise à jour la mise à jour : " >> /var/log/$loguser.auto-update.txt
date >> /home/$loguser.auto-update.txt
